function SubjectInfo = Get_SubjectInfo()

%---- get subject information  SubjectInfo
Subject_prompt={'Subject name (no space)', ...
    'Session Number (for this subject)', ...
    'gender[male, female]', ...
    'age', ...
    'Left eye sight', ...
    'Right eye sight', ...
    'Other vision info. (e.g., Depth vision)' ...
    };
dialog_title='Give_Subject_Information';
num_lines=1;
Subject_default_answer={'Zhaoping_Li','1', 'female','56','corrected','corrected', 'experimenter '};
subject_info=inputdlg(Subject_prompt,dialog_title,num_lines,Subject_default_answer);
SubjectInfo.Name  = subject_info{1};
SubjectInfo.SessionNumber = str2num(subject_info{2});
SubjectInfo.Gender = subject_info{3};
SubjectInfo.Age = str2num(subject_info{4});
SubjectInfo.LeftEyeSight = subject_info{5};
SubjectInfo.RightEyeSight = subject_info{6};
SubjectInfo.OtherVisionInfo = subject_info{7};